package com.montplex.resp;

import java.util.HashSet;
import java.util.List;

public class Category {
    private static final HashSet<String> writeCmdSet = new HashSet<>();

    private static final HashSet<String> readCmdSet = new HashSet<>();

    public static boolean isWriteCmd(String cmd) {
        return writeCmdSet.contains(cmd.toLowerCase());
    }

    public static boolean isReadCmd(String cmd) {
        return readCmdSet.contains(cmd.toLowerCase());
    }

    static {
        List<String> writeCmdList = List.of(
                "append",
                "bitfield",
                "bitop",
                "blmove",
                "blpop",
                "brpop",
                "brpoplpush",
                "bzpopmax",
                "bzpopmin",
                "copy",
                "decr",
                "decrby",
                "del",
                "expire",
                "expireat",
                "flushall",
                "flushdb",
                "geoadd",
                "georadius",
                "georadiusbymember",
                "geosearchstore",
                "getdel",
                "getex",
                "getset",
                "hdel",
                "hincrby",
                "hincrbyfloat",
                "hmset",
                "hset",
                "hsetnx",
                "incr",
                "incrby",
                "incrbyfloat",
                "linsert",
                "lmove",
                "lpop",
                "lpush",
                "lpushx",
                "lrem",
                "lset",
                "ltrim",
                "migrate",
                "move",
                "mset",
                "msetnx",
                "persist",
                "pexpire",
                "pexpireat",
                "pfadd",
                "pfdebug",
                "pfmerge",
                "psetex",
                "rename",
                "renamenx",
                "restore",
                "restore-asking",
                "rpop",
                "rpoplpush",
                "rpush",
                "rpushx",
                "sadd",
                "sdiffstore",
                "set",
                "setbit",
                "setex",
                "setnx",
                "setrange",
                "sinterstore",
                "smove",
                "sort",
                "spop",
                "srem",
                "sunionstore",
                "swapdb",
                "unlink",
                "xack",
                "xadd",
                "xautoclaim",
                "xclaim",
                "xdel",
                "xgroup",
                "xreadgroup",
                "xsetid",
                "xtrim",
                "zadd",
                "zdiffstore",
                "zincrby",
                "zinterstore",
                "zpopmax",
                "zpopmin",
                "zrangestore",
                "zrem",
                "zremrangebylex",
                "zremrangebyrank",
                "zremrangebyscore",
                "zunionstore"
        );
        writeCmdSet.addAll(writeCmdList);

        List<String> readCmdList = List.of(
                "bitcount",
                "bitfield_ro",
                "bitpos",
                "dbsize",
                "dump",
                "exists",
                "geodist",
                "geohash",
                "geopos",
                "georadius_ro",
                "georadiusbymember_ro",
                "geosearch",
                "get",
                "getbit",
                "getrange",
                "hexists",
                "hget",
                "hgetall",
                "hkeys",
                "hlen",
                "hmget",
                "host:",
                "hrandfield",
                "hscan",
                "hstrlen",
                "hvals",
                "keys",
                "lindex",
                "llen",
                "lolwut",
                "lpos",
                "lrange",
                "memory",
                "mget",
                "object",
                "pfcount",
                "post",
                "pttl",
                "randomkey",
                "scan",
                "scard",
                "sdiff",
                "sinter",
                "sismember",
                "smembers",
                "smismember",
                "srandmember",
                "sscan",
                "stralgo",
                "strlen",
                "substr",
                "sunion",
                "touch",
                "ttl",
                "type",
                "xinfo",
                "xlen",
                "xpending",
                "xrange",
                "xread",
                "xrevrange",
                "zcard",
                "zcount",
                "zdiff",
                "zinter",
                "zlexcount",
                "zmscore",
                "zrandmember",
                "zrange",
                "zrangebylex",
                "zrangebyscore",
                "zrank",
                "zrevrange",
                "zrevrangebylex",
                "zrevrangebyscore",
                "zrevrank",
                "zscan",
                "zscore",
                "zunion"
        );
        readCmdSet.addAll(readCmdList);
    }
}